// [UNITY-SKILL:SPRITEATLAS]
// [TYPE:PREBUILD]
// Generated by SpriteAtlas V2 Skill
// This script automatically generates SpriteAtlas assets during prebuild for "Opción A: Integrados"

using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.U2D;
using UnityEngine;
using UnityEngine.U2D;
using System.Linq;
using System.Collections.Generic;
using System.IO;

public class SpriteAtlasPrebuildGenerator : IPreprocessBuildWithReport
{
    public int callbackOrder => 0;

    public void OnPreprocessBuild(BuildReport report)
    {
        Debug.Log("[SpriteAtlas] Generating atlases for built-in delivery...");

        // CRITICAL: Enable Sprite Packer mode
        EditorSettings.spritePackerMode = SpritePackerMode.SpriteAtlasV2;

        // Ensure directory exists
        if (!AssetDatabase.IsValidFolder("Assets/Atlases")) AssetDatabase.CreateFolder("Assets", "Atlases");

        // Generate atlases for Art folder
        // Since there are many sprites (~1000), we'll split them or just create a master one.
        // For now, let's create a general one for Assets/Art.
        GenerateAtlasByFolder("Assets/Art", "Assets/Atlases/MainArt_Atlas.spriteatlasv2", includeInBuild: true);

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
    }

    private bool IsValidProjectSprite(string assetPath)
    {
        return assetPath.StartsWith("Assets/") && !assetPath.Contains("/Packages/");
    }

    private void GenerateAtlasByFolder(string spriteFolder, string atlasPath, bool includeInBuild)
    {
        if (!Directory.Exists(spriteFolder)) return;

        string[] guids = AssetDatabase.FindAssets("t:Sprite", new[] { spriteFolder });
        UnityEngine.Object[] sprites = guids
            .Select(g => AssetDatabase.GUIDToAssetPath(g))
            .Where(path => IsValidProjectSprite(path))
            .Select(path => AssetDatabase.LoadAssetAtPath<Sprite>(path))
            .Where(s => s != null)
            .Cast<UnityEngine.Object>()
            .ToArray();

        if (sprites.Length == 0)
        {
            Debug.LogWarning($"[SpriteAtlas] No sprites found in {spriteFolder}");
            return;
        }

        SpriteAtlasAsset atlasAsset;
        if (File.Exists(atlasPath))
        {
            atlasAsset = SpriteAtlasAsset.Load(atlasPath);
            // Clear existing to refresh
            var spriteAtlas = AssetDatabase.LoadAssetAtPath<SpriteAtlas>(atlasPath);
            if (spriteAtlas != null)
            {
                atlasAsset.Remove(spriteAtlas.GetPackables());
            }
        }
        else
        {
            atlasAsset = new SpriteAtlasAsset();
            Directory.CreateDirectory(Path.GetDirectoryName(atlasPath));
        }

        atlasAsset.Add(sprites);
        SpriteAtlasAsset.Save(atlasAsset, atlasPath);
        AssetDatabase.ImportAsset(atlasPath);

        ConfigureAtlasImporter(atlasPath, includeInBuild);

        Debug.Log($"[SpriteAtlas] Generated {atlasPath} with {sprites.Length} sprites.");
    }

    private void ConfigureAtlasImporter(string atlasPath, bool includeInBuild)
    {
        SpriteAtlasImporter importer = AssetImporter.GetAtPath(atlasPath) as SpriteAtlasImporter;
        if (importer == null) return;

        var textureSettings = importer.textureSettings;
        textureSettings.filterMode = FilterMode.Bilinear;
        textureSettings.generateMipMaps = false;
        importer.textureSettings = textureSettings;

        var packingSettings = importer.packingSettings;
        packingSettings.padding = 4;
        packingSettings.enableAlphaDilation = true;
        importer.packingSettings = packingSettings;

        // Optimization for Mobile
        SetPlatformSettings(importer, "Android", TextureImporterFormat.ASTC_6x6);
        SetPlatformSettings(importer, "iOS", TextureImporterFormat.ASTC_4x4);
        SetPlatformSettings(importer, "WebGL", TextureImporterFormat.DXT5Crunched);

        importer.includeInBuild = includeInBuild;
        importer.SaveAndReimport();
    }

    private void SetPlatformSettings(SpriteAtlasImporter importer, string platformName, TextureImporterFormat format)
    {
        var settings = new TextureImporterPlatformSettings
        {
            name = platformName,
            overridden = true,
            maxTextureSize = 2048,
            format = format,
            compressionQuality = 50
        };
        importer.SetPlatformSettings(settings);
    }
}
